from parsers.apre import ApreScraper
from parsers.areflh import AreflhScraper
from parsers.consigliodeuropait import ConsiglioDEuropaITScraper
from parsers.consiglioeuropeo import ConsiglioEuropeo
from parsers.cor import CORScraper
from parsers.cpmr import CPMRScraper
from parsers.earlall import EarlAllScraper
from parsers.eea import EEAScraper
from parsers.eib import EIBScraper
from parsers.eif import EIFScraper
from parsers.eit import EITScraper
from parsers.enicbcmed import EniCbcMedScraper
from parsers.espon import EsponScraper
from parsers.eucommission import EUCommissionScraper
from parsers.euparliament import EUParliamentScraper
from parsers.euregha import EureghaScraper
from parsers.europeanagency import EuropeanAgencyScraper
from parsers.eurostat import EurostatScraper
from parsers.eusalp import EusalpScraper
from parsers.imi import IMIScraper
from parsers.interreg import InterregScraper
from parsers.jrc import JRCScraper
from parsers.promis import PromisScraper
from parsers.ecgeneric import ECGenericScraper
from parsers.ecitalia import ECItaliaScraper
from parsers.eceducation import ECEducationScraper
from parsers.ecoceans import ECOceansScraper
from parsers.ec_regionalpolicy import ECRegionalPolicyScraper
from parsers.ecrea import ECReaScraper
